stages:
  - lint
  - build

lint:
  stage: lint
  image: torrentofshame/lualatex-texliveonfly
  script:
    - chktex simonweizman.tex

build:
  stage: build
  image: torrentofshame/lualatex-texliveonfly
  script:
    - texliveonfly --compiler=latexmk --arguments='-pdflua -interaction=nonstopmode' simonweizman.tex
  artifacts:
    paths:
      - ./*.pdf

# Cache aux files to speed things up
cache:
  untracked: true
  key: "$CI_BUILD_NAME"
